### ISSUE TITLE
Goaly stopped scheduling my goals. BUG]

### ISSUE THREAD

**Issue by Tarawssmith** [rosenpin/Goaly#39] opened 2023-03-01 14:30 UTC
Feb 28 is full of goals, March has none. My schedule stayed the same. It happened once before in Dec.  I was without goals for about two weeks and then it started up again. How can I avoid this?

![Screenshot_20230301-092526](https://user-images.githubusercontent.com/120754122/222169316-635c46aa-45bf-4ee2-adb2-4f3a79d3f328.png)

**Comment by rosenpin** [comment] 2023-03-01 14:55
try opening Goaly, make sure you have it installed   
it should schedule your goals automatically once you open it

**Comment by Tarawssmith** [comment] 2023-03-01 15:03
It is installed and opened

**Comment by rosenpin** [comment] 2023-03-01 15:18
weird, please send your logs by opening the app -> settings -> scroll down -> send logs  
we will look into it!

**Comment by rosenpin** [comment] 2023-03-01 15:19
also please try to reboot your phone and re-open the app, that might help for this time

**Comment by Tarawssmith** [comment] 2023-03-01 20:42
Reboot didn't fix it

**Comment by rosenpin** [comment] 2023-04-03 08:18
Hi, was this issue solved? Did Goaly resume scheduling? @Tarawssmith

**Comment by Tarawssmith** [comment] 2023-04-03 10:15
Not really. I think I figured it out though. It won't schedule tasks if I have an event that is spread across several days even if it is set to"free". That is frustrating.

Musically,
Tara Smith

________________________________

**Comment by rosenpin** [comment] 2023-04-03 10:19
Yes, that's it then  
We will look into fixing it ASAP

Duplicate of https://github.com/rosenpin/Goaly/issues/15

**Closed as completed by rosenpin** 2023-04-03 10:19 UTC
Labels: bug, prioritized
