### ISSUE TITLE
No reschedule on time settings change 

### ISSUE THREAD

**Issue by DMeredith88** [rosenpin/Goaly#58] opened 2023-05-03 12:52 UTC
Changing evenings to end at 9pm for example doesn't reschedule tasks for goals already set at 10pm.

**Comment by rosenpin** [comment] 2023-05-03 17:51
Thanks for the feedback  
This is a duplicate of https://github.com/rosenpin/Goaly/issues/54  
Feel free to follow this issue instead

**Closed as completed by rosenpin** 2023-05-03 17:51 UTC
Labels: duplicate

**Comment by DMeredith88** [comment] 2023-05-03 18:09
Didn't see that one! Thanks :)
