### ISSUE TITLE
[BUG] Schedule in Goaly app is different from the google calendar

### ISSUE THREAD

**Issue by lianadara** [rosenpin/Goaly#23] opened 2022-12-28 22:45 UTC
**Describe the bug**
The schedule I created in goaly app is different from google calendar. And also, I can't change the color of my schedule

**Smartphone (please complete the following information):**
 - Device: Redmi 10
 - App Version: 1.1.1
 
![Screenshot_2022-12-29-05-48-03-929_com google android calendar](https://user-images.githubusercontent.com/106791473/209882236-2ec4dc94-57c6-4131-859f-eb84208bd3da.png)
![Screenshot_2022-12-29-05-47-38-383_io rosenpin goals](https://user-images.githubusercontent.com/106791473/209882238-3af7777c-85ef-44a1-8e50-f867c11798af.png)

**Comment by rosenpin** [comment] 2022-12-29 13:00
I experience this issue as well, we'll look into it for the next release

**Comment by rosenpin** [comment] 2022-12-30 15:38
Regarding the color issue, can you please send a screenshot of how it looks when you're trying to change the color?

**Comment by lianadara** [comment] 2022-12-31 01:22
> Regarding the color issue, can you please send a screenshot of how it looks when you're trying to change the color?

I don't know how to change it, there isn't an option 
![Screenshot_2022-12-31-08-18-47-376_io rosenpin goals](https://user-images.githubusercontent.com/106791473/210120860-8f944b82-2797-492a-852a-c2baf60052da.png)

**Comment by rosenpin** [comment] 2022-12-31 11:10
This is because you didn't sign in to the app with Google Calendar (during the setup process)  
Colors are only available in the Google Calendar mode due to a limitation in Android calendar

**Comment by lianadara** [comment] 2022-12-31 12:50
> This is because you didn't sign in to the app with Google Calendar (during the setup process) Colors are only available in the Google Calendar mode due to a limitation in Android calendar

Ooh.. hmm I think I've already logged in with google calendar🤔.  But I'm not sure 😬
Can I re-sign and re-set up?  Does that not affect my subscription?

**Comment by rosenpin** [comment] 2022-12-31 13:05
You can change it by uninstalling/reinstalling the app. This will delete all your goals and progress, make sure to choose sign in with Google during the setup (this will also enable auto backup/restore)  
We will probably add an option to change between Google/non google calendar without loosing data in a future update  
This doesn't affect your subscription if you bought the premium version

**Comment by rosenpin** [comment] 2023-02-24 08:14
Fixed in the latest update and was duplicate of #25

**Closed as completed by rosenpin** 2023-02-24 08:14 UTC
Labels: bug, prioritized
