### ISSUE TITLE
[BUG]when clicking Did it! In Google Calendar, Goaly opens but then changes to blank gray screen and the item remains unmarked in Google Calendar. A Goaly reinstall will permit one Did it! But then reverts to gray screen again. iPhone 8: iOS 16.3.1

### ISSUE THREAD

**Issue by Mykluster** [rosenpin/Goaly#48] opened 2023-04-15 02:09 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by rosenpin** [comment] 2023-04-15 06:06
Thank you for bringing this to our attention!  
Can you please re-check the app version code? Are you sure it's 1.0.1? 

You can check it by going to your device settings->applications->Goaly->Scroll Down->Advanced->Version

**Comment by rosenpin** [comment] 2023-04-15 06:11
We will look into fixing it.  
You can complete your goals directly from Goaly in the upcoming screen until the issue is fixed

For now you can solve it when it happens by 
1. Opening Goaly normally
2. Force closing by swiping it away in your recent apps
3. Tapping "did it" in your calendar

**Comment by rosenpin** [comment] 2023-04-15 06:21
Fixed it!  
We'll push an update in the coming days that includes a fix for it

**Comment by Mykluster** [comment] 2023-04-15 10:46
It is version 1.1.6

**Comment by rosenpin** [comment] 2023-04-17 06:21
Fixed in version 1.1.7 available now/tomorrow

**Closed as completed by rosenpin** 2023-04-17 06:21 UTC
Labels: bug
